################################################################################
#
# Wind data: Extract monthly avg netcdf data based on coordinates generated by
# KDEs
#
################################################################################

# Clear environment -------------------------------------------------------

rm(list = ls())

# User Inputted Values -----------------------------------------------------

location = 'Bird_Island' # Options: 'Bird_Island', 'Midway'

# Packages  ---------------------------------------------------------

# require(sf)
require(tidyverse)
# require(raster)
# library(nngeo)
library(lubridate)
library(terra)
# library(stars)
# library(ncmeta)
# library(ncdf4)
# library(RNetCDF)
# library(lattice)
# library(rasterVis) #vectorplot
# library(colorRamps) #matlab.like
# library(viridisLite)
# library(colorspace)
# library(DescTools) #closest
# library(imputeTS) #na.interpolation
library(geosphere)
# library(foehnix)
# require(ggplot2)
# require(RColorBrewer)

# Set Environment ---------------------------------------------------------

# GD_dir <- "/Users/ian/Library/CloudStorage/GoogleDrive-ian.maywar@stonybrook.edu/.shortcut-targets-by-id/1-mLOKt79AsOpkCFrunvcUj54nuqPInxf/THORNE_LAB/Data/Albatross/NEW_STRUCTURE/"
GD_dir <- "/Users/ian/Library/CloudStorage/GoogleDrive-ian.maywar@stonybrook.edu/My Drive/NEW_STRUCTURE/"

# nc_dir <- paste0(GD_dir,"L0/",location,"/Wind_Data/ERA5_Monthly_Avg_10m/")
nc_dir <- "/Users/ian/Desktop/TEMPDATA/"

GPS_dir <- paste0(GD_dir,"L4/",location,"/Tag_Data/GPS/")

# User Functions ----------------------------------------------------------

wrap360 <- function(lon) {lon360<-ifelse(lon<0,lon+360,lon);return(lon360)}

Lon360to180 <- function(lon){
  ((lon + 180) %% 360) - 180
}

# Both bearings must be [0,360)
bearingAngle <- function(bird_bearing,wind_bearing) {
  LHturn <- wrap360(bird_bearing - wind_bearing)
  RHturn <- wrap360(wind_bearing - bird_bearing)
  return(pmin(LHturn,RHturn))
}

# Get compiled GPS data of all birds in szn ------

setwd(GPS_dir)
files <- list.files(pattern='*.csv') # GPS files 
m <- read.csv(files[1])
m_list <- as.list(m)

max(m$lat)
min(m$lat)                         
Lon360to180(max(m$lon))
Lon360to180(min(m$lon))

# Download the netcdf files from https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form

setwd(nc_dir)
wind_files <- list.files(pattern='*.nc') 

# Extract wind data -----------------------------------------------

# Load netcdf file directly for Bird Island
wind_t1 <- rast(wind_files[1])
# Create data vectors
wind_t1 # Make sure you got the right stuff!
times_t1 <- time(wind_t1)  # stores times from each file 
all_times <- unique(times_t1) # find unique values because there should be two of every datetime (for u and v)
all_times_num <- as.numeric(all_times)


# Loop through m and add wind information: u, v ---------------------------

# create u and v wind vectors

for (j in 1:length(m[[1]])) {
  
  # isolate coordinates
  xy_j <- as.data.frame(cbind(m$lon[j], m$lat[j]))
  colnames(xy_j) <- c("lon","lat")
  
  # Extract u and v components for time j at location x and y
  speed_j <- extract(wind_t1, xy_j, ID=FALSE)
  
  monthly_avgs <- as.data.frame(t(speed_j))
  colnames(monthly_avgs) <- c("speed")
  monthly_avgs$datetime <- time(wind_t1)
  
  # Create yearly avg dataframe
  yr_avg <- monthly_avgs %>% 
    group_by(year(datetime)) %>% 
    summarise(Average = mean(speed))
    
  yearly_avgs <- as.data.frame(yr_avg)
  colnames(yearly_avgs) <- c("year","speed")
  
  # add to list
  m_list$monthly[j] <- list(monthly_avgs)
  m_list$yearly[j] <- list(yearly_avgs)
  
}



# Now that I have all of the wind data for each location what do i do?
# I could find the average of the yearly averages for 2018_2022 for the entirety of the area
# covered by the KDE

poly1_idx <- which(m_list$Polygon==1)
poly2_idx <- which(m_list$Polygon==2)
poly3_idx <- which(m_list$Polygon==3)
poly4_idx <- which(m_list$Polygon==4)

# wait. even if i have average monthly measurements for u and v components of wind
# THis doesn't necessarily make sense when im concerned with average windspeed. 
# Do I look for a different source? 










