################################################################################
#
# Wind data: Extract monthly avg netcdf data based on coordinates generated by
# KDEs
#
################################################################################

# Clear environment -------------------------------------------------------

rm(list = ls())

# User Inputted Values -----------------------------------------------------

locations = c('Bird_Island','Midway') # Options: 'Bird_Island', 'Midway'

# Packages  ---------------------------------------------------------

require(tidyverse)
library(lubridate)
library(terra)
library(geosphere)
library(raster)

# User Functions ----------------------------------------------------------

wrap360 <- function(lon) {lon360<-ifelse(lon<0,lon+360,lon);return(lon360)}

Lon360to180 <- function(lon){
  ((lon + 180) %% 360) - 180
}

# Both bearings must be [0,360)
bearingAngle <- function(bird_bearing,wind_bearing) {
  LHturn <- wrap360(bird_bearing - wind_bearing)
  RHturn <- wrap360(wind_bearing - bird_bearing)
  return(pmin(LHturn,RHturn))
}

# Process both sites -----------------------------------------------------------

GD_dir <- "/Users/ian/Library/CloudStorage/GoogleDrive-ian.maywar@stonybrook.edu/My Drive/Thorne Lab Shared Drive/Data/Albatross/"
write_dir <- paste0(GD_dir,"/Analysis/Maywar/Wind_KDEs")

for (loc_idx in 1:length(locations)) {
  location <- locations[loc_idx]

  # Set Environment ---------------------------------------------------------
  
  if (location == 'Bird_Island') {
    nc_dir <- paste0(GD_dir,"L0/",location,"/Wind_Data/compiled_2019_2022/ERA5_Monthly_Avg_10m/")
  } else if (location == 'Midway') {
    nc_dir <- paste0(GD_dir,"L0/",location,"/Wind_Data/compiled_2018_2023/ERA5_Monthly_Avg_10m/")
  }
  GPS_dir <- paste0(GD_dir,"L4/",location,"/Tag_Data/GPS/")
  
  # Get wind data raster ---------------------------------------------------------
  
  # Download the netcdf files from https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form
  
  setwd(nc_dir)
  wind_files <- list.files(pattern='*.nc') 
  
  if (location == "Bird_Island") {
    
    # Load netcdf file directly for Bird Island
    wind_t1 <- rast("Bird_Island_19_22.nc")
    # Create data vectors
    wind_t1 # Make sure you got the right stuff!
    times_t1 <- time(wind_t1)  # stores times from each file 
    all_times <- unique(times_t1) # find unique values because there should be two of every datetime (for u and v)
    all_times_num <- as.numeric(all_times)
    
  } else if (location == "Midway") {
    
    # Load netcdf file directly for Midway
    wind_t1 <- rast("Midway_18_23.nc")
    wind_t1 # Make sure you got the right stuff!
    
    # Wrap -180 to 180
    wind_crds <- as.data.frame(crds(wind_t1[[1]]))
    for (lyr_name in names(wind_t1)) {
      new_crds <- cbind(wind_crds,as.data.frame(values(wind_t1[[lyr_name]])))
      new_crds_neg180 <- new_crds %>% filter(x==-180)
      new_crds_neg180$x <- 180
      new_crds <- rbind(new_crds,new_crds_neg180)
      new_crds <- arrange(new_crds,desc(y),x)
      current_lyr <- rast(new_crds,type="xyz")
      if (lyr_name == names(wind_t1)[1]) {
        wind_t1_new <- current_lyr
      } else {
        wind_t1_new <- c(wind_t1_new,current_lyr)
      }
    }
    time(wind_t1_new) <- time(wind_t1)
    units(wind_t1_new) <- units(wind_t1)
    
    # Create data vectors
    wind_t1 <- wind_t1_new # Make sure you got the right stuff!
    wind_t1

    times_t1 <- time(wind_t1)  # stores times from each file 
    all_times <- unique(times_t1) # find unique values because there should be two of every datetime (for u and v)
    all_times_num <- as.numeric(all_times)
    
  }
  
  # Get compiled GPS data of all birds in szn ------------------------------------
  
  setwd(GPS_dir)
  files <- list.files(pattern='*.csv') # GPS files 
  
  for (file_idx in 1:length(files)) {
    m <- read_csv(files[file_idx])
    m$WindSpeed <- NA
    
    BirdSpp <- strsplit(files[file_idx],"_")[[1]][1] 
    TripType <- strsplit(files[file_idx],"_")[[1]][2]
    BirdSpp
    TripType
    
    if (BirdSpp %in% c("BBAL","GHAL")) {
      if (TripType == "Inc") {
        # months <- c("October","November","December")
        months <- c(10,11,12)
      } else if (TripType == "BG") {
        # months <- c("January-April")
        months <- 1:4
      } else if (TripType == "all") {
        months <- c(10:12,1:4)
        off_months <- 6:8
      }
    } else if (BirdSpp %in% c("BFAL","LAAL")) {
      if (TripType == "Inc") {
        # months <- c("November", "December","January")
        months <- c(11,12,1)
      } else if (TripType == "BG") {
        # months <- c("Feb-Jun")
        months <- 2:6
      } else if (TripType == "all") {
        months <- c(11:12,1:6)
        off_months <- 8:10
      }
    } else if (BirdSpp == "WAAL") {
      if (TripType == "Inc") {
        # months <- c("December","January","February")
        months <- c(12,1,2)
      } else if (TripType == "BG") {
        # months <- c("March","April-November")
        months <- 3:11
      } else if (TripType == "all") {
        months <- c(1:12)
      }
    }
    
    
    # Loop through coordinates and find wind speed data --------------------------
    
    ncoords <- nrow(m)
    
    # Create off-colony figures for all spp except WAAL (never off-colony)
    if (BirdSpp != "WAAL" & TripType=="all") {
      off_m <- m
    }
    
    for (j in 1:ncoords) {
      
      # isolate coordinates
      xy_j <- as.data.frame(cbind(m$lon[j], m$lat[j]))
      colnames(xy_j) <- c("lon","lat")
      
      # Extract speed for time j at location x and y
      speed_j <- extract(wind_t1, xy_j, ID=FALSE)
      
      if (nrow(speed_j)==0) {
        
      }
      
      monthly_avgs <- as.data.frame(t(speed_j))
      colnames(monthly_avgs) <- c("speed")
      monthly_avgs$datetime <- time(wind_t1)
      
      # Sometimes there are NA values for some reason...
      monthly_avgs <- na.omit(monthly_avgs)
      
      # Remove unwanted mth/yrs...
      if (location == "Bird_Island") {
        monthly_avgs <- monthly_avgs %>% filter(
          datetime > as.Date("2019-06-01") & datetime < as.Date("2022-06-01"))
      } else if (location == "Midway") {
        monthly_avgs <- monthly_avgs %>% filter(
          (datetime > as.Date("2018-06-01") & datetime < as.Date("2019-06-01")) |
            (datetime > as.Date("2021-06-01") & datetime < as.Date("2023-06-01")))
      }

      # Create off-colony figures for all spp except WAAL (never off-colony)
      if (BirdSpp != "WAAL" & TripType=="all") {
        off_monthly_avgs <- monthly_avgs
      }
      
      # Trim data so that only the months you are interested are kept
      monthly_avgs <- monthly_avgs %>% filter(month(datetime) %in% months)
      if (BirdSpp != "WAAL" & TripType=="all") {
        off_monthly_avgs <- off_monthly_avgs %>% filter(month(datetime) %in% off_months)
      }
      
      # Add Speed data to m and m_all_mths
      m$WindSpeed[j] <- mean(monthly_avgs$speed)
      if (BirdSpp != "WAAL" & TripType=="all") {
        off_m$WindSpeed[j] <- mean(off_monthly_avgs$speed)
      }
    }
    
    # Add species and trip type info
    m$Spp <- BirdSpp
    m$TripType <- TripType
    
    if (BirdSpp != "WAAL" & TripType=="all") {
      off_m$Spp <- BirdSpp
      off_m$TripType <- "off"
      Spp_TT_df <- rbind(m,off_m)
    } else {
      Spp_TT_df <- m
    }
    
    if (loc_idx == 1 & file_idx == 1) {
      compiled_df <- Spp_TT_df
    } else {
      compiled_df <- rbind(compiled_df,Spp_TT_df)
    }
  }
}

write_csv(compiled_df,file=paste0(write_dir,"KDEs_compiled_breeding_szn_avgs.csv"))


# Plot wind data ----------------------------------------------------------

# Read csv if necessary
compiled_df <- read_csv(paste0(write_dir,"KDEs_compiled_breeding_szn_avgs.csv"))

# Re-order spp groups
compiled_df$Spp <- factor(compiled_df$Spp , levels=c("BBAL","GHAL","WAAL","BFAL","LAAL"))
compiled_df$TripType <- factor(compiled_df$TripType , levels=c("all","off","Inc","BG"))
compiled_df$TripType <- recode(compiled_df$TripType,"all"="on")

# Create plot for on and off colony wind data
ggplot(compiled_df %>% filter(TripType=="on" | TripType=="off"), aes(x = Spp, y = WindSpeed, fill=TripType)) +
  scale_fill_brewer(palette = "Set1") +
  geom_boxplot() +
  labs(title = "", x = "Species", y = "Average WindSpeed") +
  ylim(0,12)

# Create plot for Inc and BG wind data
ggplot(compiled_df %>% filter(TripType=="Inc" | TripType=="BG"), aes(x = Spp, y = WindSpeed, fill=TripType)) +
  scale_fill_brewer(palette = "Set2") +
  geom_boxplot() +
  labs(title = "", x = "Species", y = "Average WindSpeed") +
  ylim(0,12)


# Plot wind data for all months-------------------------------------------------

# Re-order spp groups
Spp_TT_df_all_mths$Spp <- factor(Spp_TT_df_all_mths$Spp , levels=c("BBAL", "GHAL", "BFAL", "LAAL"))


plot_Spp_TT_mth <- ggplot(Spp_TT_df_all_mths, aes(x = Spp, y = Nov, fill=TripType)) +
  geom_boxplot() +
  labs(title = "Nov", x = "Species", y = "Average WindSpeed") +
  theme_minimal() +
  ylim(0,13)
plot_Spp_TT_mth


