################################################################################
#
# Wind data: Extract monthly avg netcdf data based on coordinates generated by
# KDEs
#
################################################################################

# Clear environment -------------------------------------------------------

rm(list = ls())

# User Inputted Values -----------------------------------------------------

locations = c('Bird_Island','Midway') # Options: 'Bird_Island', 'Midway'

# Packages  ---------------------------------------------------------

require(tidyverse)
library(lubridate)
library(terra)
library(geosphere)

# User Functions ----------------------------------------------------------

wrap360 <- function(lon) {lon360<-ifelse(lon<0,lon+360,lon);return(lon360)}

Lon360to180 <- function(lon){
  ((lon + 180) %% 360) - 180
}

# Both bearings must be [0,360)
bearingAngle <- function(bird_bearing,wind_bearing) {
  LHturn <- wrap360(bird_bearing - wind_bearing)
  RHturn <- wrap360(wind_bearing - bird_bearing)
  return(pmin(LHturn,RHturn))
}

# Process both sites -----------------------------------------------------------


for (loc_idx in 1:length(locations)) {
  location <- locations[loc_idx]

  # Set Environment ---------------------------------------------------------
  
  GD_dir <- "/Users/ian/Library/CloudStorage/GoogleDrive-ian.maywar@stonybrook.edu/.shortcut-targets-by-id/1-mLOKt79AsOpkCFrunvcUj54nuqPInxf/THORNE_LAB/Data/Albatross/NEW_STRUCTURE/"
  nc_dir <- paste0(GD_dir,"L0/",location,"/Wind_Data/ERA5_Monthly_Avg_10m/")
  GPS_dir <- paste0(GD_dir,"L4/",location,"/Tag_Data/GPS/")
  
  # Get wind data raster ---------------------------------------------------------
  
  # Download the netcdf files from https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form
  
  setwd(nc_dir)
  wind_files <- list.files(pattern='*.nc') 
  
  if (location == "Bird_Island") {
    
    # Load netcdf file directly for Bird Island
    wind_t1 <- rast(wind_files[1])
    # Create data vectors
    wind_t1 # Make sure you got the right stuff!
    times_t1 <- time(wind_t1)  # stores times from each file 
    all_times <- unique(times_t1) # find unique values because there should be two of every datetime (for u and v)
    all_times_num <- as.numeric(all_times)
    
  } else if (location == "Midway") {
    
    # Load netcdf file directly for Midway
    wind_neg_t1 <- rast(wind_files[1]) # negative longitudinal coordinates
    wind_pos_t1 <- rast(wind_files[2]) # positive longitudinal coordinates
    wind_t1 <- merge(wind_neg_t1,wind_pos_t1)
    
    # Create data vectors
    wind_t1 # Make sure you got the right stuff!
    times_t1 <- time(wind_t1)  # stores times from each file 
    all_times <- unique(times_t1) # find unique values because there should be two of every datetime (for u and v)
    all_times_num <- as.numeric(all_times)
    
  }
  
  # Get compiled GPS data of all birds in szn ------------------------------------
  
  setwd(GPS_dir)
  files <- list.files(pattern='*.csv') # GPS files 
  
  for (file_idx in 1:length(files)) {
    m <- read.csv(files[file_idx])
    m_all_mths <- m
    
    BirdSpp <- strsplit(files[file_idx],"_")[[1]][1] 
    TripType <- strsplit(files[file_idx],"_")[[1]][2]
    BirdSpp
    TripType
    
    if (BirdSpp %in% c("BBAL","GHAL")) {
      if (TripType == "Inc") {
        # months <- c("October","November","December")
        months <- c(10,11,12)
      } else if (TripType == "BG") {
        # months <- c("December","January","February")
        months <- c(12,1,2)
      }
    } else if (BirdSpp %in% c("BFAL","LAAL")) {
      if (TripType == "Inc") {
        # months <- c("November", "December","January")
        months <- c(11,12,1)
      } else if (TripType == "BG") {
        # months <- c("January","February","March")
        months <- c(1,2,3)
      }
    }
    
    
    # Loop through coordinates and find wind speed data --------------------------
    
    ncoords <- nrow(m)
    for (j in 1:ncoords) {
      
      # isolate coordinates
      xy_j <- as.data.frame(cbind(m$lon[j], m$lat[j]))
      colnames(xy_j) <- c("lon","lat")
      
      # Extract speed for time j at location x and y
      speed_j <- extract(wind_t1, xy_j, ID=FALSE)
      
      monthly_avgs <- as.data.frame(t(speed_j))
      colnames(monthly_avgs) <- c("speed")
      monthly_avgs$datetime <- time(wind_t1)
      
      # Sometimes there are NA values for some reason...
      monthly_avgs <- na.omit(monthly_avgs)
      
      # Remove unwanted mth/yrs...
      if (location == "Bird_Island") {
        monthly_avgs <- monthly_avgs %>% filter(
          datetime > as.Date("2019-06-01") & datetime < as.Date("2022-06-01"))
      } else if (location == "Midway") {
        monthly_avgs <- monthly_avgs %>% filter(
          (datetime > as.Date("2018-06-01") & datetime < as.Date("2019-06-01")) |
            (datetime > as.Date("2021-06-01") & datetime < as.Date("2023-06-01")))
      }
      
      # Subset into seasons
      all_monthly_avgs <- monthly_avgs
      
      # Trim data so that only the months you are interested are kept
      monthly_avgs <- monthly_avgs %>% filter(month(datetime) %in% months)
      
      # Add Speed data to m and m_all_mths
      m$WindSpeed[j] <- mean(monthly_avgs$speed)
      
      m_all_mths$Jan[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==1))$speed)
      m_all_mths$Feb[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==2))$speed)
      m_all_mths$Mar[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==3))$speed)
      m_all_mths$Apr[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==4))$speed)
      m_all_mths$May[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==5))$speed)
      m_all_mths$Jun[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==6))$speed)
      m_all_mths$Jul[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==7))$speed)
      m_all_mths$Aug[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==8))$speed)
      m_all_mths$Sep[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==9))$speed)
      m_all_mths$Oct[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==10))$speed)
      m_all_mths$Nov[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==11))$speed)
      m_all_mths$Dec[j] <- mean((all_monthly_avgs %>% filter(month(datetime)==12))$speed)
      
    }
    
    # Store everything in a dataframe
    m$Spp <- BirdSpp
    m$TripType <- TripType
    m_all_mths$Spp <- BirdSpp
    m_all_mths$TripType <- TripType
    
    if (loc_idx == 1 & file_idx == 1) {
      Spp_TT_df <- m
      Spp_TT_df_all_mths <- m_all_mths
    } else {
      Spp_TT_df <- rbind(Spp_TT_df,m)
      Spp_TT_df_all_mths <- rbind(Spp_TT_df_all_mths,m_all_mths)
    }
    
  }

}



# Plot wind data ----------------------------------------------------------

# Re-order spp groups
Spp_TT_df$Spp <- factor(Spp_TT_df$Spp , levels=c("BBAL", "GHAL", "BFAL", "LAAL"))

# Create plot
plot_Spp_TT <- ggplot(Spp_TT_df, aes(x = Spp, y = WindSpeed, fill=TripType)) +
  geom_boxplot() +
  labs(title = "", x = "Species", y = "Average WindSpeed") +
  theme_minimal()
plot_Spp_TT


# Plot wind data for all months-------------------------------------------------

# Re-order spp groups
Spp_TT_df_all_mths$Spp <- factor(Spp_TT_df_all_mths$Spp , levels=c("BBAL", "GHAL", "BFAL", "LAAL"))

# Create plot for Jan wind data
plot_Spp_TT_mth <- ggplot(Spp_TT_df_all_mths, aes(x = Spp, y = Apr, fill=TripType)) +
  geom_boxplot() +
  labs(title = "", x = "Species", y = "Average WindSpeed") +
  theme_minimal()
plot_Spp_TT_mth


