################################################################################
#
# Env data: Extract monthly avg netcdf data based on coordinates generated by KDEs
# This will create averages during brood guard, incubation, all on-colony months,
# and all off-colony months. This will also create monthly averages.
#
################################################################################

# Clear environment ------------------------------------------------------------

rm(list = ls())

# User Inputted Values ---------------------------------------------------------

location = 'Midway' # Options: 'Bird_Island', 'Midway'

# Packages  --------------------------------------------------------------------

require(tidyverse)
library(lubridate)
library(terra)
library(geosphere)
library(raster)
library(rgdal)
library(tidyterra)
library(geosphere)

# User Functions ----------------------------------------------------------

wrap360 <- function(lon) {lon360<-ifelse(lon<0,lon+360,lon);return(lon360)}

Lon360to180 <- function(lon){
  ((lon + 180) %% 360) - 180
}

# Both bearings must be [0,360)
bearingAngle <- function(bird_bearing,wind_bearing) {
  LHturn <- wrap360(bird_bearing - wind_bearing)
  RHturn <- wrap360(wind_bearing - bird_bearing)
  return(pmin(LHturn,RHturn))
}

weighted_avg <- function(x, w) {
  sum(x * w,na.rm=TRUE) / sum(w)
}

# Set environment --------------------------------------------------------------

GD_dir <- "/Users/ian/Library/CloudStorage/GoogleDrive-ian.maywar@stonybrook.edu/My Drive/Thorne Lab Shared Drive/Data/Albatross/"
write_dir <- paste0(GD_dir,"L1/",location,"/Env_Data/ERA5_MonthlyAvg_10m/")

if (location == "Bird_Island") {
  setwd(paste0(GD_dir,"L2/Bird_Island/Tag_Data/GPS/compiled_2019_2022/compiled_by_spp/"))
  nc_wind_dir <- paste0(GD_dir,"L0/",location,"/Env_Data/compiled_2019_2022/ERA5_Wind_MonthlyAvg_10m/")
  nc_wave_dir <- paste0(GD_dir,"L0/",location,"/Env_Data/compiled_2019_2022/ERA5_Wave_MonthlyAvg_10m/")
} else if (location == "Midway") {
  setwd(paste0(GD_dir,"L2/Midway/Tag_Data/GPS/compiled_2018_2023/compiled_by_spp/"))
  nc_wind_dir <- paste0(GD_dir,"L0/",location,"/Env_Data/compiled_2019_2023/ERA5_Wind_MonthlyAvg_10m/")
  nc_wave_dir <- paste0(GD_dir,"L0/",location,"/Env_Data/compiled_2019_2023/ERA5_Wave_MonthlyAvg_10m/")
}

GPS_dir <- paste0(GD_dir,"L4/",location,"/Tag_Data/GPS/")
files <- list.files(pattern='*.csv') # GPS files 

# Create compiled file
for (i in 1:length(files)) {
  mi <- read_csv(files[i])
  if (i==1) {
    m <- mi
  } else {
    m<- rbind(m,mi)
  }
}

m$datetime <- as.POSIXct(m$datetime,format="%Y-%m-%d %H:%M:%S", tz="GMT")

# Make sure all birds are found within the grid extent
# Bird Island grid extent: -30N -70S -120W -10E (big range due to Wandering!)
# Midway grid extent: 50N 20S 140W -140E
# NOTE: Midway data must be downloaded in two parts because you cannot cross the 
# 180 lon line when specifying grid extent: latN latS lonW 180 (E_Midway) and 
# latN latS -180 latE (W_Midway)

# Download 10m windspeed as one netCDF
# Then, download the wave variables as another netCDF:
#   Mean direction of total swell, Mean period of total swell, Significant height
#   of total swell, Mean direction of wind waves, Mean period of wind waves,
#   Mean wave direction, Mean wave period, Significant height of combined wind
#   waves and swell, and Significant height of wind waves

max(m$lat)
min(m$lat)                         
Lon360to180(max(m$lon))
Lon360to180(min(m$lon))
min(m$datetime)
max(m$datetime)

# Get env data rasters ---------------------------------------------------------

if (location == "Bird_Island") {
  
  # Wind data
  setwd(nc_wind_dir)
  wind_raster <- rast("Bird_Island_19_22.nc")
  crs(wind_raster)  <- "epsg:4326"
  wind_raster # Make sure you got the right stuff!
  
  new_wind_columns <- unique(varnames(wind_raster))
  
  # Wave data
  setwd(nc_wave_dir)
  wave_raster <- rast("Bird_Island_19_22.nc")
  crs(wave_raster)  <- "epsg:4326"
  wave_raster # Make sure you got the right stuff!
  
  new_wave_columns <- unique(varnames(wave_raster))
  
} else if (location == "Midway") {
  
  # Wind data
  # COMBINE E AND W COMPONENTS OF NETCDF FILES for Midway
  setwd(nc_wind_dir)
  wind_E_component <- rast("Midway_19_23_E.nc")
  crs(wind_E_component)  <- "epsg:4326"
  wind_W_component <- rast("Midway_19_23_W.nc")
  crs(wind_W_component)  <- "epsg:4326"
  
  # The following times are missing from wind_E_component:
  # "2022-01-01 UTC" ([37]), "2023-02-01 UTC" ([49]), "2023-11-01 UTC" ([59])
  wind_E_component_patch <- wind_E_component
  add(wind_E_component_patch) <- terra::subset(wind_E_component,55:57)
  wind_E_component_patch[,,37] <- NA # "2022-01-01 UTC"
  wind_E_component_patch[,,38:58] <- terra::subset(wind_E_component,37:57)
  wind_E_component_patch[,,50] <- NA # "2023-02-01 UTC"
  wind_E_component_patch[,,51:59] <- terra::subset(wind_E_component,49:57)
  wind_E_component_patch[,,59] <- NA # "2023-11-01 UTC"
  wind_E_component_patch[,,60] <- terra::subset(wind_E_component,57)
  names(wind_E_component_patch) <- names(wind_W_component)
  terra::time(wind_E_component_patch) <- terra::time(wind_W_component)
  
  wind_raster <- terra::merge(wind_E_component_patch,wind_W_component)
  crs(wind_raster)  <- "epsg:4326"
  wind_raster # Make sure you got the right stuff!
  
  new_wind_columns <- unique(varnames(wind_W_component))
  
  # Wave data
  setwd(nc_wave_dir)
  wave_files <- list.files(pattern='*.nc')
  wave_E_component <- rast("Midway_19_23_E.nc")
  crs(wave_E_component)  <- "epsg:4326"
  wave_W_component <- rast("Midway_19_23_W.nc")
  crs(wave_W_component)  <- "epsg:4326"
  wave_raster <- terra::merge(wave_E_component,wave_W_component)
  crs(wave_raster)  <- "epsg:4326"
  wave_raster # Make sure you got the right stuff!
  
  new_wave_columns <- unique(unlist(str_split(names(wave_raster), "_"))[seq(1,2*length(names(wave_raster)),2)])
  
}

# Get compiled GPS data of all birds in szn ------------------------------------

setwd(GPS_dir)
KDEs <- list.files(recursive = FALSE) # GPS files 

for (KDE_idx in 1:length(KDEs)) {
  KDE_name <- KDEs[KDE_idx]
  Polygons <- vect(KDE_name)
  
  BirdSpp <- strsplit(KDE_name,"_")[[1]][1] 
  TripType <- strsplit(KDE_name,"_")[[1]][2]
  BirdSpp
  TripType
  
  if (BirdSpp %in% c("BBAL","GHAL")) {
    if (TripType == "Inc") {
      months_on <- 10:12
      months_off <- 1:9
    } else if (TripType == "BG") {
      months_on <- 1:5
      months_off <- 6:12
    } else if (TripType == "all") {
      months_on <- c(1:5,9:12)
      months_off <- 6:8
    }
  } else if (BirdSpp %in% c("BFAL","LAAL")) {
    if (TripType == "Inc") {
      months_on <- c(1,11,12)
      months_off <- 2:10
    } else if (TripType == "BG") {
      months_on <- 2:6
      months_off <- c(1,7:12)
    } else if (TripType == "all") {
      months_on <- c(1:7,11:12)
      months_off <- 8:10
    }
  } else if (BirdSpp == "WAAL") {
    if (TripType == "Inc") {
      months_on <- c(1,2,12)
      months_off <- 3:11
    } else if (TripType == "BG") {
      months_on <- 3:11
      months_off <- c(1,2,12)
    } else if (TripType == "all") {
      months_on <- c(1:12)
    }
  }
  
  # Extract env data -----------------------------------------------------------
  
  # Plot polygons
  Polygon_df <- as.data.frame(geom(Polygons))
  Polygons_lon360 <- terra::rotate(Polygons,left=FALSE)
  Polygon_lon360_df <- as.data.frame(geom(Polygons_lon360))
  ggplot(Polygon_lon360_df, aes(x,y,group=part)) +
    geom_path()
  
  # Polygons that go over the 180 longitude line introduce weird complications.
  if (location=="Midway") {
    wind_raster_lon360 <- terra::rotate(wind_raster,left=FALSE)
    wave_raster_lon360 <- terra::rotate(wave_raster,left=FALSE)
    for (prt in unique(Polygon_lon360_df$part)) {
      Polygons_lon360_prt <- vect(as.matrix(Polygon_lon360_df %>% filter(part==prt)),"polygons")
      wind_data_prt <- terra::extract(wind_raster_lon360, Polygons_lon360_prt, ID=FALSE, xy=TRUE, weights=TRUE)
      wave_data_prt <- terra::extract(wave_raster_lon360, Polygons_lon360_prt, ID=FALSE, xy=TRUE, weights=TRUE)
      if (prt==1) {
        wind_data <- wind_data_prt
        wave_data <- wave_data_prt
      } else {
        wind_data <- rbind(wind_data,wind_data_prt)
        wave_data <- rbind(wave_data,wave_data_prt)
      }
    }
  } else if (location == "Bird_Island") {
    wind_data <- terra::extract(wind_raster, Polygons, ID=FALSE, xy=TRUE, weights=TRUE)
    wave_data <- terra::extract(wave_raster, Polygons, ID=FALSE, xy=TRUE, weights=TRUE)
    wind_data <- wind_data %>%
      mutate(x = ifelse(x < 0, x + 360, x))
  }
  
  # Plot wind and wave data to make sure that the extracted points are actually found within the KDEs
  ggplot(wind_data, aes(x,y)) +
    geom_point()
  ggplot(wave_data, aes(x,y)) +
    geom_point()
  
  # Trim data so that only the months_on you are interested are kept
  wind_data_on <- wind_data[,c(which(month(as.POSIXct(as.numeric(time(wind_raster)),tz="GMT")) %in% months_on),ncol(wind_data))]
  wave_data_on <- wave_data[,c(which(month(as.POSIXct(as.numeric(time(wave_raster)),tz="GMT")) %in% months_on),ncol(wave_data))]
  
  # Create off-colony data for KDEs
  # NOTE: WAALs are never "off-colony"
  if (!(BirdSpp == "WAAL" & TripType == "all")) {
    wind_data_off <- wind_data[,c(which(month(as.POSIXct(as.numeric(time(wind_raster)),tz="GMT")) %in% months_off),ncol(wind_data))]
    wave_data_off <- wave_data[,c(which(month(as.POSIXct(as.numeric(time(wave_raster)),tz="GMT")) %in% months_off),ncol(wave_data))]
  }
  
  # For wind speed
  poly_avg_wind_on <- t(wind_data_on %>%
    summarise(across(.cols = -weight, .fns = ~ weighted_avg(., weight), .names = "weighted_avg_{col}")))
  colnames(poly_avg_wind_on) <- new_wind_columns
  rownames(poly_avg_wind_on) <- NULL
  
  # For wave variables
  for (wave_var in new_wave_columns) {
    wave_data_on_var <- wave_data_on[,c(which(do.call(rbind,strsplit(colnames(wave_data_on), "_"))[,1] == wave_var),ncol(wave_data_on))]
    poly_avg_wave_on_var <- t(wave_data_on_var %>%
      summarise(across(.cols = -weight, .fns = ~ weighted_avg(., weight), .names = "weighted_avg_{col}")))
    colnames(poly_avg_wave_on_var) <- wave_var
    rownames(poly_avg_wave_on_var) <- NULL
    
    if (wave_var == new_wave_columns[1]) {
      poly_avg_wave_on <- poly_avg_wave_on_var
    } else {
      poly_avg_wave_on <- cbind(poly_avg_wave_on,poly_avg_wave_on_var)
    }
  }
  
  # Combine wind and wave data and add metadata
  poly_avg_env <- as.data.frame(cbind(poly_avg_wind_on,poly_avg_wave_on))
  if (location == "Bird_Island") {
    poly_avg_env$Month <- rep(months_on,4)
  } else if (location == "Midway") {
    poly_avg_env$Month <- rep(months_on,5)
  }

  poly_avg_env$Species <- BirdSpp
  poly_avg_env$KDE_type <- TripType
  poly_avg_env$on_colony <- 1
  
  # For off-colony
  if (!(BirdSpp == "WAAL" & TripType == "all")) {

    # For wind speed
    poly_avg_wind_off <- t(wind_data_off %>%
                            summarise(across(.cols = -weight, .fns = ~ weighted_avg(., weight), .names = "weighted_avg_{col}")))
    colnames(poly_avg_wind_off) <- new_wind_columns
    rownames(poly_avg_wind_off) <- NULL
    
    # For wave variables
    for (wave_var in new_wave_columns) {
      wave_data_off_var <- wave_data_off[,c(which(do.call(rbind,strsplit(colnames(wave_data_off), "_"))[,1] == wave_var),ncol(wave_data_off))]
      poly_avg_wave_off_var <- t(wave_data_off_var %>%
                                  summarise(across(.cols = -weight, .fns = ~ weighted_avg(., weight), .names = "weighted_avg_{col}")))
      colnames(poly_avg_wave_off_var) <- wave_var
      rownames(poly_avg_wave_off_var) <- NULL
      
      if (wave_var == new_wave_columns[1]) {
        poly_avg_wave_off <- poly_avg_wave_off_var
      } else {
        poly_avg_wave_off <- cbind(poly_avg_wave_off,poly_avg_wave_off_var)
      }
    }
    
    # Combine wind and wave data and add metadata
    poly_avg_env_off <- as.data.frame(cbind(poly_avg_wind_off,poly_avg_wave_off))
    if (location == "Bird_Island") {
      poly_avg_env_off$Month <- rep(months_off,4)
    } else if (location == "Midway") {
      poly_avg_env_off$Month <- rep(months_off,5)
    }
    
    poly_avg_env_off$Species <- BirdSpp
    poly_avg_env_off$KDE_type <- TripType
    poly_avg_env_off$on_colony <- 0
    
    # Add off-colony data to on-colony data.
    poly_avg_env <- rbind(poly_avg_env,poly_avg_env_off)
    
  }
  
  if (KDE_idx == 1) {
    compiled_df <- poly_avg_env
  } else {
    compiled_df <- rbind(compiled_df,poly_avg_env)
  }
}

write_csv(compiled_df,file=paste0(write_dir,location,"_KDEs_avg_env.csv"))
