################################################################################
#
# Wind data: Extract monthly avg netcdf data based on coordinates generated by
# KDEs
#
################################################################################

# Clear environment -------------------------------------------------------

rm(list = ls())

# User Inputted Values -----------------------------------------------------

locations = c('Bird_Island','Midway') # Options: 'Bird_Island', 'Midway'

# Packages  ---------------------------------------------------------

require(tidyverse)
library(lubridate)
library(terra)
library(geosphere)
library(raster)
library(rgdal)

# User Functions ----------------------------------------------------------

wrap360 <- function(lon) {lon360<-ifelse(lon<0,lon+360,lon);return(lon360)}

Lon360to180 <- function(lon){
  ((lon + 180) %% 360) - 180
}

# Both bearings must be [0,360)
bearingAngle <- function(bird_bearing,wind_bearing) {
  LHturn <- wrap360(bird_bearing - wind_bearing)
  RHturn <- wrap360(wind_bearing - bird_bearing)
  return(pmin(LHturn,RHturn))
}

# Process both sites -----------------------------------------------------------

GD_dir <- "/Users/ian/Library/CloudStorage/GoogleDrive-ian.maywar@stonybrook.edu/My Drive/Thorne Lab Shared Drive/Data/Albatross/"
write_dir <- paste0(GD_dir,"/Analysis/Maywar/Wind_KDEs/")

for (loc_idx in 1:length(locations)) {
  location <- locations[loc_idx]

  # Set Environment ---------------------------------------------------------
  
  if (location == 'Bird_Island') {
    nc_dir <- paste0(GD_dir,"L0/",location,"/Env_Data/compiled_2019_2022/ERA5_Wind_Monthly_Avg_10m/")
  } else if (location == 'Midway') {
    nc_dir <- paste0(GD_dir,"L0/",location,"/Env_Data/compiled_2018_2023/ERA5_Wind_Monthly_Avg_10m/")
  }
  GPS_dir <- paste0(GD_dir,"L4/",location,"/Tag_Data/GPS/")
  
  # Get wind data raster ---------------------------------------------------------
  
  # Download the netcdf files from https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form
  
  setwd(nc_dir)
  wind_files <- list.files(pattern='*.nc') 
  
  if (location == "Bird_Island") {
    
    # Load netcdf file directly for Bird Island
    wind_t1 <- rast("Bird_Island_19_22.nc")
    # Create data vectors
    wind_t1 # Make sure you got the right stuff!
    times_t1 <- time(wind_t1)  # stores times from each file 
    all_times <- unique(times_t1) # find unique values because there should be two of every datetime (for u and v)
    all_times_num <- as.numeric(all_times)
    
  } else if (location == "Midway") {
    
    # Load netcdf file directly for Midway
    wind_t1 <- rast("Midway_18_23.nc")
    wind_t1 # Make sure you got the right stuff!
    
    # Wrap -180 to 180
    wind_crds <- as.data.frame(crds(wind_t1[[1]]))
    for (lyr_name in names(wind_t1)) {
      new_crds <- cbind(wind_crds,as.data.frame(values(wind_t1[[lyr_name]])))
      new_crds_neg180 <- new_crds %>% filter(x==-180)
      new_crds_neg180$x <- 180
      new_crds <- rbind(new_crds,new_crds_neg180)
      new_crds <- arrange(new_crds,desc(y),x)
      current_lyr <- rast(new_crds,type="xyz")
      if (lyr_name == names(wind_t1)[1]) {
        wind_t1_new <- current_lyr
      } else {
        wind_t1_new <- c(wind_t1_new,current_lyr)
      }
    }
    time(wind_t1_new) <- time(wind_t1)
    units(wind_t1_new) <- units(wind_t1)
    
    # Create data vectors
    wind_t1 <- wind_t1_new # Make sure you got the right stuff!
    wind_t1

    times_t1 <- time(wind_t1)  # stores times from each file 
    all_times <- unique(times_t1) # find unique values because there should be two of every datetime (for u and v)
    all_times_num <- as.numeric(all_times)
    
  }
  
  # Get compiled GPS data of all birds in szn ------------------------------------
  
  setwd(GPS_dir)
  KDEs <- list.dirs(recursive = FALSE) # GPS files 
  KDEs <- str_sub(KDEs,3,)
  
  for (KDE_idx in 1:length(KDEs)) {
    KDE_name <- KDEs[KDE_idx]
    Polygons <- vect(paste0(KDE_name,"/",KDE_name,".shp"))
    
    BirdSpp <- strsplit(KDE_name,"_")[[1]][1] 
    TripType <- strsplit(KDE_name,"_")[[1]][2]
    BirdSpp
    TripType
    
    if (BirdSpp %in% c("BBAL","GHAL")) {
      if (TripType == "Inc") {
        # months <- c("October","November","December")
        months <- c(10,11,12)
      } else if (TripType == "BG") {
        # months <- c("January-April")
        months <- 1:4
      } else if (TripType == "all") {
        months <- c(10:12,1:4)
        off_months <- 6:8
      }
    } else if (BirdSpp %in% c("BFAL","LAAL")) {
      if (TripType == "Inc") {
        # months <- c("November", "December","January")
        months <- c(11,12,1)
      } else if (TripType == "BG") {
        # months <- c("Feb-Jun")
        months <- 2:6
      } else if (TripType == "all") {
        months <- c(11:12,1:6)
        off_months <- 8:10
      }
    } else if (BirdSpp == "WAAL") {
      if (TripType == "Inc") {
        # months <- c("December","January","February")
        months <- c(12,1,2)
      } else if (TripType == "BG") {
        # months <- c("March","April-November")
        months <- 3:11
      } else if (TripType == "all") {
        months <- c(1:12)
      }
    }
    
    # Extract wind_vel data ----------------------------------------------------
    speed_j <- terra::extract(wind_t1, Polygons, ID=TRUE, xy=TRUE)
    colnames(speed_j) <- c("ID",times_t1,"x","y")
  
    # Remove unwanted mth/yrs...
    if (location == "Bird_Island") {
      speed_j <- speed_j %>% dplyr::select(as.character((as.numeric(
                  times_t1[which(
                    times_t1 > as.Date("2019-06-01") & 
                    times_t1 < as.Date("2022-06-01"))]))))
    } else if (location == "Midway") {
      speed_j <- speed_j %>% dplyr::select(as.character((as.numeric(
                  times_t1[which(
                    (times_t1 > as.Date("2018-06-01") & times_t1 < as.Date("2019-06-01")) |
                    (times_t1 > as.Date("2021-06-01") & times_t1 < as.Date("2023-06-01")))]))))
    }

    # Create off-colony data for KDEs created by TripType == "all"
    # NOTE: WAALs are never "off-colony"
    if (BirdSpp != "WAAL" & TripType=="all") {
      off_speed_j <- speed_j
    }
      
    # Trim data so that only the months you are interested are kept
    speed_j <- speed_j[,c(which(month(as.POSIXct(as.numeric(colnames(speed_j)[2:ncol(speed_j)]),tz="GMT")) %in% months))]

    if (BirdSpp != "WAAL" & TripType=="all") {
      off_speed_j <- off_speed_j[,c(which(month(as.POSIXct(as.numeric(colnames(off_speed_j)[2:ncol(off_speed_j)]),tz="GMT")) %in% off_months))]
    }
      
    # Store data in a dataframe
    m <- data.frame(t((summarize_all(speed_j,mean))))
    rownames(m) <- NULL
    colnames(m) <- "WindVel"
    m$Month <- as.numeric(colnames(speed_j))
    m$Species <- BirdSpp
    m$TripType <- TripType
    
    if (BirdSpp != "WAAL" & TripType=="all") {
      off_m <- data.frame(t((summarize_all(off_speed_j,mean))))
      rownames(off_m) <- NULL
      colnames(off_m) <- "WindVel"
      off_m$Month <- as.numeric(colnames(off_speed_j))
      off_m$Species <- BirdSpp
      off_m$TripType <- "off"
      m <- rbind(m,off_m)
    }
    
    if (loc_idx == 1 & KDE_idx == 1) {
      compiled_df <- m
    } else {
      compiled_df <- rbind(compiled_df,m)
    }
  }
}

write_csv(compiled_df,file=paste0(write_dir,"KDEs_compiled_breeding_szn_avgs.csv"))


# Plot wind data ----------------------------------------------------------

# Read csv if necessary
write_dir <- paste0(GD_dir,"/Analysis/Maywar/Wind_KDEs/")
compiled_df <- read_csv(paste0(write_dir,"KDEs_compiled_breeding_szn_avgs.csv"))

# Re-order spp groups
compiled_df$Species <- factor(compiled_df$Species, levels=c("BBAL","GHAL","WAAL","BFAL","LAAL"))
compiled_df$TripType <- factor(compiled_df$TripType , levels=c("all","off","Inc","BG"))
compiled_df <- compiled_df %>%  mutate(TripType = recode_factor(TripType, "all" = "on"))

# Create plot for on and off colony wind data
ggplot(compiled_df %>% filter(TripType=="on" | TripType=="off"), aes(x = Species, y = WindVel, fill=TripType)) +
  scale_fill_brewer(palette = "Set1") +
  geom_boxplot() +
  labs(title = "", x = "Species", y = "Average WindSpeed") +
  # ylim(0,12) + 
  scale_y_continuous(limits=c(0,12),
                     breaks=seq(0,12,by=2)) +
  theme_bw()

# Create plot for Inc and BG wind data
ggplot(compiled_df %>% filter(TripType=="Inc" | TripType=="BG"), aes(x = Species, y = WindVel, fill=TripType)) +
  scale_fill_brewer(palette = "Set2") +
  geom_boxplot() +
  labs(title = "", x = "Species", y = "Average WindSpeed") +
  ylim(0,12)

# Create plot for all on-colony data
ggplot(compiled_df %>% filter(TripType=="on"), aes(x = Species, y = WindVel)) +
  scale_fill_brewer(palette = "Set2") +
  geom_boxplot() +
  labs(title = "", x = "Species", y = "Average WindSpeed") +
  scale_y_continuous(limits=c(0,12),
                     breaks=seq(0,12,by=2)) +
  theme_bw()
